name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Запускается при пуше тега, начинающегося с 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run start.sh
        run: chmod +x ./start.sh && ./start.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          for file in *.dat; do
            if [ -f "$file" ]; then
              gh release upload ${{ steps.create_release.outputs.upload_url }} "$file" --clobber
            fi
          done
